version: '3.7'
services:
  app:
    container_name: app
    build: 
      context: "./app"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
volumes:
  app: